version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-didacta_db}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    restart: always
    expose:
      - "8000"
    depends_on:
      db_mysql:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DB_HOST=db_mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-didacta_db}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-rootpassword}
      # Atlas Mongo URI will be injected by Coolify env vars
      - MONGO_URI=${MONGO_URI} 
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80" # Exposed to Coolify's proxy
    depends_on:
      - backend

volumes:
  mysql_data:
