# Generated by Django 5.1.3 on 2025-11-05 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_evento_planificacion_calendario_planificaciondetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('tipo_periodo', models.CharField(choices=[('SEMESTRE', 'Semestral'), ('TRIMESTRE', 'Trimestral'), ('ANUAL', 'Anual')], default='SEMESTRE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Año Académico',
                'verbose_name_plural': 'Años Académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.RemoveField(
            model_name='evento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='planificaciondetalle',
            name='planificacion',
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado Nacional'), ('INSTITUCIONAL', 'Día Institucional'), ('RECESO', 'Receso Académico')], default='FERIADO', max_length=15)),
                ('anio_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='main.anioacademico')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='main.anioacademico')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['anio_academico', 'numero'],
                'unique_together': {('anio_academico', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('INVIERNO', 'Vacaciones de Invierno'), ('VERANO', 'Vacaciones de Verano'), ('RECESO', 'Receso Académico')], max_length=10)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='main.anioacademico')),
            ],
            options={
                'verbose_name': 'Periodo de Vacaciones',
                'verbose_name_plural': 'Periodos de Vacaciones',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='PlanificacionDetalle',
        ),
    ]
