# Generated by Django 5.1.3 on 2025-11-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_anioacademico_remove_evento_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anioacademico',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
