# Generated by Django 5.1.3 on 2025-11-05 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_anioacademico_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='anio_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones', to='main.anioacademico'),
        ),
    ]
