# Generated by Django 5.1.3 on 2025-11-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_planificacion_anio_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='anioacademico',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='anioacademico',
            name='activo',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='anioacademico',
            name='cerrado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
