# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_anioacademico_estado_alter_anioacademico_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='anio_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones', to='main.anioacademico'),
        ),
    ]