# Generated by Django 5.1.3 on 2025-11-19 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_planificacion_anio_academico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre_asignatura'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nivel', 'nombre_curso'],
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionAnual',
            fields=[
                ('planificacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.planificacion')),
                ('meses_academicos', models.IntegerField(default=12)),
                ('periodos_evaluacion', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Planificación Anual',
                'verbose_name_plural': 'Planificaciones Anuales',
            },
            bases=('main.planificacion',),
        ),
        migrations.CreateModel(
            name='RecursoPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recurso Pedagógico',
                'verbose_name_plural': 'Recursos Pedagógicos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='planificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Planificación', 'verbose_name_plural': 'Planificaciones'},
        ),
        migrations.AddField(
            model_name='planificacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='anio_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='main.anioacademico'),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='tipo',
            field=models.CharField(choices=[('ANUAL', 'Planificación Anual'), ('UNIDAD', 'Planificación de Unidad'), ('SEMANAL', 'Planificación Semanal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('UTP', 'UTP'), ('EQUIPO_DIRECTIVO', 'Equipo Directivo')], default='DOCENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='main.asignatura'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='main.curso'),
        ),
        migrations.CreateModel(
            name='CursoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curso')),
            ],
            options={
                'verbose_name': 'Curso-Asignatura',
                'verbose_name_plural': 'Cursos-Asignaturas',
                'unique_together': {('curso', 'asignatura')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='asignaturas',
            field=models.ManyToManyField(related_name='cursos', through='main.CursoAsignatura', to='main.asignatura'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('especialidad', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_a_cargo', to='main.docente'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='main.docente'),
        ),
        migrations.CreateModel(
            name='EquipoDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_directivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo Directivo',
                'verbose_name_plural': 'Equipo Directivo',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='main.niveleducativo'),
        ),
        migrations.CreateModel(
            name='ObjetivoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='main.curso')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='main.niveleducativo')),
            ],
            options={
                'verbose_name': 'Objetivo de Aprendizaje',
                'verbose_name_plural': 'Objetivos de Aprendizaje',
            },
        ),
        migrations.AddField(
            model_name='planificacion',
            name='objetivos_aprendizaje',
            field=models.ManyToManyField(blank=True, related_name='planificaciones', to='main.objetivoaprendizaje'),
        ),
        migrations.CreateModel(
            name='PlanificacionUnidad',
            fields=[
                ('planificacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.planificacion')),
                ('numero_unidad', models.IntegerField()),
                ('semanas_duracion', models.IntegerField(default=4)),
                ('planificacion_anual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='main.planificacionanual')),
            ],
            options={
                'verbose_name': 'Planificación de Unidad',
                'verbose_name_plural': 'Planificaciones de Unidad',
                'ordering': ['numero_unidad'],
            },
            bases=('main.planificacion',),
        ),
        migrations.CreateModel(
            name='PlanificacionSemanal',
            fields=[
                ('planificacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.planificacion')),
                ('numero_semana', models.IntegerField()),
                ('horas_academicas', models.IntegerField(default=45)),
                ('planificacion_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='main.planificacionunidad')),
            ],
            options={
                'verbose_name': 'Planificación Semanal',
                'verbose_name_plural': 'Planificaciones Semanales',
                'ordering': ['numero_semana'],
            },
            bases=('main.planificacion',),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='recursos_pedagogicos',
            field=models.ManyToManyField(blank=True, related_name='planificaciones', to='main.recursopedagogico'),
        ),
    ]
