# Generated by Django 5.1.3 on 2025-12-08 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_add_comprehensive_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-anio_academico__fecha_inicio', 'nivel', 'nombre_curso'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='anio_academico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='main.anioacademico'),
        ),
        migrations.AddField(
            model_name='curso',
            name='archivado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
