# Generated by Django 5.1.3 on 2025-12-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_curso_options_curso_anio_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='capacidad_maxima',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='curso',
            name='paralelo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
