# Generated by Django 5.1.3 on 2025-12-09 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_curso_capacidad_maxima_curso_paralelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoasignatura',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_asignadas', to='main.docente'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='curso_asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='main.cursoasignatura'),
        ),
        migrations.AlterField(
            model_name='cursoasignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_asignadas', to='main.curso'),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_legacy', to='main.asignatura'),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_legacy', to='main.curso'),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_legacy', to='main.docente'),
        ),
    ]
