# Generated by Django 5.1.3 on 2025-12-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cursoasignatura_docente_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
