# Generated by Django 5.1.3 on 2025-12-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='plan_asociado',
            field=models.CharField(blank=True, default='', help_text='Plan al que pertenece (solo para electivos)', max_length=20),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='tipo',
            field=models.CharField(choices=[('COMUN', 'Común'), ('ELECTIVO', 'Electivo')], default='COMUN', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='plan_diferenciado',
            field=models.CharField(blank=True, choices=[('', 'No aplica'), ('MEDIO_1_2', '1°-2° Medio'), ('CH', 'Científico-Humanista'), ('TP', 'Técnico Profesional'), ('ARTISTICO', 'Artístico')], default='', help_text='Plan diferenciado para Educación Media (3°-4°)', max_length=20),
        ),
    ]
