# Generated by Django 5.1.3 on 2025-12-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_plan_diferenciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='es_multicurso',
            field=models.BooleanField(default=False, help_text='Permite combinar cursos (electivos, Ed.Física)'),
        ),
        migrations.AddField(
            model_name='cursoasignatura',
            name='horas_semanales',
            field=models.PositiveIntegerField(default=4, help_text='Horas pedagógicas semanales (definido por UTP)'),
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número de bloque (1-10)')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='main.anioacademico')),
            ],
            options={
                'verbose_name': 'Bloque Horario',
                'verbose_name_plural': 'Bloques Horario',
                'ordering': ['numero'],
                'unique_together': {('numero', 'anio_academico')},
            },
        ),
        migrations.CreateModel(
            name='GrupoMulticurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Electivo Biología III-IV, Ed.Física 1°-2° Básico', max_length=100)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_multicurso', to='main.anioacademico')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_multicurso', to='main.asignatura')),
                ('cursos', models.ManyToManyField(related_name='grupos_multicurso', to='main.curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_multicurso', to='main.docente')),
            ],
            options={
                'verbose_name': 'Grupo Multicurso',
                'verbose_name_plural': 'Grupos Multicurso',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='main.asignatura')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='main.bloquehorario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='main.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='main.docente')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'bloque__numero'],
                'unique_together': {('curso', 'dia_semana', 'bloque')},
            },
        ),
    ]
